spring.application.name=reportes
server.port=8084


jwt.secret=LJHDz9Rtrbmp3Ewz617QkLZbOt60nb6tF9eB6d4fauw=


venta.url=http://localhost:8082
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

